# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: daechoi <daechoi@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/04/21 16:16:30 by daechoi           #+#    #+#              #
#    Updated: 2022/04/21 17:23:56 by daechoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -L./mlx -lmlx -framework OpenGL -framework AppKit *.c get_next_line/*.c utils/*.c
	./a.out map.ber